Add status checks for the database and sqs services to the /livez endpoint
adobe/cluster-registry pull request #10
Opened 2022-02-04 15:28 UTC by palasanu

## Description

Add status checks for the database and sqs services to the /livez endpoint.
With it, I also added two metrics that count the errors from the status checks: database_status_error_count, sqs_status_error_count

## Motivation and Context

Before the endpoint just checked if the API was up and running, now there are connectivity checks that can identify if one of the underlying services can be reached.

## How Has This Been Tested?

Tested the changes locally with mocks.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-02-04 16:14 UTC, palasanu commented
Rerun tests

2022-02-09 08:31 UTC, victorvarza requested changes
Looks good overall! Let't discuss the metric for target errors.

2022-02-09 08:31 UTC, victorvarza commented on pkg/api/database/database_test.go
> +		},
Let's add also a happy path test.

2022-02-09 08:31 UTC, victorvarza commented on pkg/api/monitoring/metrics.go
> +	ID:          "DatabaseStatusErrCnt",
What is the benefit of recording this metric?

2022-02-09 08:31 UTC, victorvarza commented on pkg/api/monitoring/metrics.go
> +	ID:          "SqsStatusErrCnt",
Same here.

2022-02-09 08:31 UTC, victorvarza commented on pkg/api/monitoring/metrics.go
> +	databaseStatusErrCnt, sqsStatusErrCnt *prometheus.CounterVec
We should't have specifics in this module. Instead we can record errors in general as `errCnt`

2022-02-14 20:25 UTC, victorvarza approved these changes

2022-02-14 20:25 UTC, merged