Add performance tests with its make target
adobe/cluster-registry pull request #19
Opened 2022-02-28 20:13 UTC by palasanu

Add performance tests with its make target

## Motivation and Context

We needed some performance tests so we can see how the project performs over time.

After this, a mechanism that runs these tests automatically should be added.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-03-02 12:03 UTC, victorvarza requested changes
Looking good! 
Small changes from my side as performance test tool should be considered a separate app and it's makefile targets build/release should live outside of the main Makefile.

2022-03-02 15:19 UTC, palasanu commented on Makefile
> +IMAGE_TAG_PERFORMENCE=latest
Sound good, I will make the changes when I find some time

2022-03-11 12:46 UTC, palasanu commented
run tests

2022-03-16 19:06 UTC, palasanu commented on Makefile
> -	-X $(GO_PKG)/version.Revision=$(BUILD_REVISION)  \
I tried to pass the variables to the config package, but it did not work. I tried on the database package and it worked, I'm could not figure out why it did not work on the config package so I left them on the main.

2022-03-18 10:57 UTC, victorvarza approved these changes

2022-03-18 10:57 UTC, merged